from app.models import db, Product

def seed_products():
  products=[
    Product(
      owner_id=1, name="Peptide Pro Firming Moisturizer", category="Worry Free", price=43, shortdescript="A next-gen proven wrinkle cream for all ages.", description='Have it all with Peptide Pro Firming Moisturizer: visibly reverse lines and wrinkles, deeply hydrate, and restore your skin barrier. Firming ingredients can deliver more visible results when skin is also hydrated and the skin barrier is healthy. We crafted a next-generation wrinkle cream that includes a hydrating moisturizer and skin barrier repair cream in the formula – to supercharge your results. We challenged the notion of thicker, traditional wrinkle creams for more mature skin only. Collagen production starts to decline in your twenties, so we firmly (pun intended!) wanted this wrinkle cream to be for all ages. Lightweight enough for all ages and all skin types, potent enough for more intensive and deeply etched wrinkles and loss of firmness.'
    ),
    Product(
      owner_id=1, name="Glass Skin Refining Serum", category="Worry Free", price=39, shortdescript="Achieve your healthiest, smoothest, clearest and most luminous skin yet", description='Glassy, smooth, luminous, translucent-looking skin is achieved when skin is well hydrated and without inflammation and free radical damage. A revolutionary cocktail of peach extract, niacinamide, East Asian mountain yam, madecassoside, peptides, and hyaluronic acid help to visibly hydrate, calm, brighten and firm skin. Crystal-clear glass skin is yours.'
    ),
    Product(
      owner_id=1, name="Glass Skin Discovery Kit", category="Worry Free", price=39  , shortdescript="Your definitive Glass Skin routine – in four easy steps", description="Glass skin: skin that's so healthy that pores look super smooth and skin looks luminous and clarified. If you're looking to achieve your glass skin goals, welcome, you've come to the right place. Peach & Lily introduced Glass Skin to the U.S. and are creators of the award-winning, #1 bestselling Glass Skin serum. We've helped countless people achieve their glass skin goals, no matter their skin type or skin concern. Our Discovery Kit is a unique, four-step routine of hero products that help you achieve Glass Skin quickly."
    ),
    Product(
      owner_id=1, name="Ginger Melt Oil Cleanser", category="Worry Free", price=32, shortdescript="A modern oil cleanser that melts and removes all with zero residue, zero breakouts.", description="Melt and remove all makeup, SPF, excess oil and impurities – within seconds. Oil cleansing can be accompanied by leftover-mascara, breakouts or a waxy residue. Ginger Melt Oil Cleanser is your modern oil cleanser crafted with zero compromises. Here's how it works: First, even the toughest makeup and SPF melt off with ease. Confidently use your white towels again. No makeup stains here."
    ),
    Product(
      owner_id=2, name="Power Calm Hydrating Gel Cleanser", category="Worry Free", price=28, shortdescript="Power Calm your skin", description="The Power Calm cleanser is uniquely formulated to respect the skin's natural ecosystem while cleansing deeply and thoroughly. The result? Pure, clean skin that's hydrated and deeply calmed. We worked with our partner lab and pulled out all the stops in cosmetic wizardry to create this next-generation cleanser. Two powerful yet gentle sulfate-free cleansing agents do the heavy-lifting in drawing out impurities."
    ),
    Product(
      owner_id=2, name="Wild Dew Treatment Essence", category="Worry Free", price=39, shortdescript="Leaves you feeling as fresh as a daisy", description='An essence may just be the missing step in your routine. Both potent and hydrating, essences not only help fight breakouts, improve skin’s radiance and impart long-lasting hydration, but they are also formulated to sink deep and fast into skin. Using next-gen technology, Peach & Lily’s nod to the Korean beauty staple includes clean, fast-acting extracts that will leave you looking and feeling fresh as a daisy.'
    ),
    Product(
      owner_id=2, name="Matcha Pudding Antioxidant Cream", category="Worry Free", price=40, shortdescript="Drenches skin with antioxidants", description="This cream addresses real life head-on. If you've ever wondered why you might be seeing premature and rapid signs of aging, you're not alone. Our skin bears increasing stress from heightened pollution, fast-paced stressful lives, excess sun exposure and lack of sleep leading to more free radical damage. The Matcha Pudding Antioxidant Cream drenches skin with antioxidants deep within skin and also creates a weightless, invisible antioxidant barrier to help fight off free radical damage at all layers of the skin."
    ),
    Product(
      owner_id=2, name="Power Cocktail Lactic Acid Repair Serum", category="Worry Free", price=49, shortdescript="10 percent lactic acid and 12 natural extracts actively resurface and repair", description="Not your typical lactic acid serum. This unique power cocktail combines 10% lactic acid with 12 active extracts, each with special properties to deliver visible results. Our potent yet gentle formula is ideal for tackling even stubborn age-related skin issues and visibly restoring youth. It also helps prevent accelerated signs of aging."
    ),
    Product(
      owner_id=3, name="Snail Rescue Purifying Cleanser", category="Pear Slices", price=14.99, shortdescript="Deep cleanses, refreshes, and purifies skin with snail mucin and pine bark extract.", description="An antibacterial, cruelty-free ingredient that's harvested from natural surfaces that snails slither around on in lush Jeju Island. Benefits include hydration, blemish-fighting, exfoliating, and dark-spot-targeting of the skin. (No snails were harmed in the making of this product!)"
    ),
    Product(
      owner_id=3, name="Snail Rescue Intensive Serum", category="Pear Slices", price=17.99, shortdescript="Concentrated snail mucin, cica, and pine bark in a deep-absorbing formula.", description="If you love Snail Mucin and you're looking for a concentrated dose in a formula that will absorb deeply for enhanced results, this serum is for you. Our high-quality, pure, 95% Snail Mucin concentrate combined with cica and pine bark works hard for your skin to deliver dramatic, visible results. The clear, cushiony yet fast-absorbing texture disappears into skin while plumping it up with hydration."
    ),
    Product(
      owner_id=3, name="Snail Rescue All-In-One Deep Moisture Cream", category="Pear Slices", price=16.99, shortdescript="Snail mucin, squalane, and cica rescue dry, dull skin.", description="A deeply moisturizing cream for dry skin that delivers all the upsides of our pure Snail Mucin concentrate. Our unique formula combines Snail Mucin with squalane, shea butter, and hydrating hyaluronic acid of various weights to provide intensive and lasting moisturization. In typical Snail Rescue fashion, the texture remains lightweight and does not clog pores. Skin is also treated with soothing cica as well as refining and calming pine bark."
    ),
    Product(
      owner_id=3, name="Snail Rescue Oil Free Moisturizer", category="Pear Slices", price=16.99, shortdescript="Quench thirsty skin and achieve a clear, shine-free glow", description="We know the dilemma faced by oily, combination, and acne-prone skin types: a too-heavy moisturizer causes breakouts, but a too-light moisturizer causes even more oil production. This refreshing, gel-texture moisturizer strikes the perfect balance. It deeply hydrates, doesn't clog pores, and provides enough lasting moisturization so that skin stays supple all day. Snail mucin hydrates, keeps skin smooth-sailing and delivers an even glow."
    ),
    Product(
      owner_id=4, name="Snail Rescue Blemish Busting Toner", category="Pear Slices", price=13.99, shortdescript="Clear pores & zap zits fast", description="Meet the ultimate power couple: two celebrated and time-tested K-Beauty ingredients, snail mucin and cica, uniquely come together to give you super-sized results. This one-of-a-kind breakthrough pairing helps clear pores, zap zits, calm signs of redness, and strengthen your skin barrier. And of course, no snails are harmed! Peach Slices is cruelty-free, Leaping-Bunny certified. The formula is clean, effective and free of filler ingredients to bring your skin only goodness."
    ),
    Product(
      owner_id=4, name="Snail Rescue Intensive Wash-Off Mask", category="Pear Slices", price=16.99, shortdescript="Targets blemishes, dark spots, pores and dullness - fast", description="Jelly isn't just for your toast. Our unique 'snail jelly' mask feels instantly refreshing and calming as it's applied onto skin. This intensive treatment clears skin and targets dark spots, blemishes, pores, and dullness. Once it's removed, all that's left is radiantly hydrated clear skin. All thanks to 95% snail mucin and cica infused with birch juice and licorice."
    ),
    Product(
      owner_id=4, name="Snail Rescue Trio", category="Pear Slices", price=47, shortdescript="3-step routine for calmer, clearer skin", description="Featuring a blend of two superstar ingredients, Snail Mucin and Cica, the Snail Rescue trio does it all: hydrates, exfoliates, fights blemishes, targets dark spots — all without clogging pores. Well-known for its healing, soothing, antibacterial, and inflammatory properties, making it ideal for sensitive skin."
    ),
    Product(
      owner_id=4, name="Redness Relief Soothing Cleanser", category="Pear Slices", price=16.99, shortdescript="Deep cleans sensitive skin without stripping or causing irritation.", description="Redness or signs of irritation? No problem. This pH-balanced formula gently cleanses and removes all impurities while supporting your skin barrier. A unique blend of panthenol, green algae, allantoin, and rhodomyrtus extract visibly reduce signs of redness and soothe skin. Formulated specifically to minimize the appearance of redness and promote skin strength, this Soothing Cleanser gives you a peaceful start to your routine."
    ),
    Product(
      owner_id=5, name="Glass Skin Discovery Kit", category="Skincare Kits", price=39, shortdescript="Your definitive Glass Skin routine – in four easy steps", description="Glass skin: skin that's so healthy that pores look super smooth and skin looks luminous and clarified. If you're looking to achieve your glass skin goals, welcome, you've come to the right place. Peach & Lily introduced Glass Skin to the U.S. and are creators of the award-winning, #1 bestselling Glass Skin serum. We've helped countless people achieve their glass skin goals, no matter their skin type or skin concern."
    ),
    Product(
      owner_id=5, name="Original Glow Sheet Mask Set", category="Skincare Kits", price=79, shortdescript="Well rested, happy, and ultra hydrated skin in the palm of your hands", description="This mask delivers the original glow you have when you're at your best – well rested, happy, and ultra hydrated skin in the palm of your hands. Potent anti-aging, hydrating, and brightening botanicals, peptides and AHA are artfully combined to give you radiant, bouncy skin. We created this mask after our original Dream Sheet Mask series received so much love. You asked for more masks and many masks, in a set for all your daily sheet-masking needs."
    ),
    Product(
      owner_id=5, name="Lagom Mini Travel Kit", category="Skincare Kits", price=29, shortdescript="Give the gift of perfectly hydrated skin", description="Featuring the bestsellers from Lagom's line-up of skincare basics, this kit is too good to resist. One little bag contains an ideal gel-type morning cleanser that can even replace your make-up removing oil cleanser, a bubbly foaming cleanser, the beloved mist toner and the Deep Moisture Cream. Love them so much you can't be without them? We've linked out to the full size products down below so you can fill the travel size containers for any weekend away. You'll never have to be without perfect skin."
    ),
    Product(
      owner_id=5, name="Glass Skin Routine Kit", category="Skincare Kits", price=175, shortdescript="An easy routine to help you achieve the glass skin of your dreams", description="Glass skin is healthy, hydrated skin that’s calm, plumped, and free of inflammation, skin that looks poreless, luminous, and translucent. If that sounds like impossible skin goals, worry not! We put together this easy routine to help you achieve the glass skin of your dreams. Power Calm Hydrating Gel Cleanser: Cleansing is the first step of any routine, and it should be thorough but gentle. The Power Calm Hydrating Gel Cleanser is sulfate-free with a pH of 5.5 and cleanses skin without stripping it dry or disrupting the natural skin barrier."
    ),
    Product(
      owner_id=6, name="Korean Skincare Regimen: Oily / Acne-Prone Skin", category="Skincare Kits", price=296, shortdescript="For those struggling with shine/prone to breakouts", description="This routine was hand-selected by our estheticians keeping in mind all the many struggles that come with having oily skin. These products are star products on their own, but were selected as they also work very well together. Meet your ultimate Korean routine kit for oily or acne-prone skin!"
    ),
    Product(
      owner_id=6, name="Korean Skincare Regimen: Combination Skin", category="Skincare Kits", price=324, shortdescript="Manage a variety of skincare issues from acne to dry flakes to shine", description="This skincare regimen is for those who have combination skin and find themselves struggling to manage a variety of skincare issues ranging from acne to dry flakes to shine. Each product in this kit has been vetted by our estheticians for combination skin -- and have been selected for how well they work together. The regimen focuses on helping to create a more supportive skin environment. This means more balance, more radiance, and less shine or flakes."
    ),
    Product(
      owner_id=6, name="Korean Skincare Regimen: Dry Skin", category="Skincare Kits", price=320, shortdescript="Bring that inner glow out, finally", description="If you have dry skin, you may lack sufficient oils on the skin's barrier. Additionally, you may be lacking hydration (moisture, not oils). This skincare regimen is appropriate for those who lack sufficient sebum production and generally also lack hydration because dry, brittle skin barriers often lead to a whole lot of moisture leaving the skin."
    ),
    Product(
      owner_id=6, name="Korean Skincare Regimen: Normal Skin", category="Skincare Kits", price=340, shortdescript="Take your skin to another level of flawless", description="This kit is focused on giving your skin all the comprehensive care it needs to stay radiant, hydrated, and firmed up. Even if you have normal skin, without proper care, normal skin also experiences breakouts, accelerated signs of aging, and irritation. The great news is that with proper support, your skin can truly stay in great shape. We included two popular cleansers to get your double cleanse right: cleanse down to pores dissolving makeup and oil-based impurities without stripping skin of your natural lipids."
    ),
    Product(
      owner_id=7, name="Acne Spot Dots - 60 Count", category="Bestsellers", price=8.99, shortdescript="Help blemishes disappear quickly and effectively with our #1 bestselling blemish solution!*", description="Our small, translucent and fast-acting acne patches actively absorb developing blemishes or already-present pimples. The sticker-like hydrocolloid patches act as a protective cover to keep you from picking while quickly and effectively helping to reduce inflammation so that blemishes become visibly smaller in less than one day. The transparent, adhesive dots come in 3 different sizes that can be worn night or day- with or without makeup."
    ),
    Product(
      owner_id=7, name="Deep Blemish Microdarts", category="Bestsellers", price=8.99, shortdescript="Microdart patches for emerging and underground blemishes", description="Fast-acting Microdart patches help rapidly diminish and calm zits. Why Microdarts? Miniscule, self-dissolving darts — saturated with clarifying salicylic acid, tea tree and willow bark, plus soothing niacinamide and cica, all in a hyaluronic acid hydrating base — precisely target the intended area for fast, visible improvement. Our signature Microdart Melt-Tech™ Technology boasts 176 Microdarts (more than any other brand!) that self-dissolve deep into skin to deliver ingredients that precisely target stubborn blemishes."
    ),
    Product(
      owner_id=7, name="Dark Spot Microdarts", category="Bestsellers", price=8.99, shortdescript="Microdart patches for dark spots and hyperpigmentation", description="Fast-acting Microdart patches help rapidly improve the appearance of discolored spots. Why Microdarts? Miniscule, self-dissolving darts — saturated with brightening niacinamide, licorice and Vitamin C, plus hydrating hyaluronic acid and cica — precisely target hyperpigmentation for fast, visible improvement. Our signature Microdart Melt-Tech™ Technology boasts 176 Microdarts (more than any other brand!) that self-dissolve deep into skin to deliver ingredients that precisely target dark or red spots."
    ),
    Product(
      owner_id=7, name="Transparen-C Pro Spot Treatment", category="Bestsellers", price=43, shortdescript="Stable 20% Vitamin C visibly erases dark spots - rapidly and gently", description="This powerful 20% Vitamin C spot treatment leaves dark spots, hyperpigmentation and scarring looking brighter, more even-toned and more transparent. Our professional-grade formula sinks deep into skin for dramatic, visible results. Ferulic acid and vitamin E boost brightening effects, while kojic and tranexamic acid gently renew skin for faster results. Our third party study shows visible results as early as 14 days of daily usage. Dark spots look erased without the irritation thanks to the gentle nature of our stable Vitamin C derivative, Ascorbyl Tetraisopalmitate, combined with soothing licorice and nourishing camellia. Ideal for all skin types, even the most sensitive skin."
    ),
    Product(
      owner_id=8, name="Ginger Melt Oil Cleanser", category="Bestsellers", price=32, shortdescript="A modern oil cleanser that melts and removes all with zero residue, zero breakouts.", description="Melt and remove all makeup, SPF, excess oil and impurities – within seconds. Oil cleansing can be accompanied by leftover-mascara, breakouts or a waxy residue. Ginger Melt Oil Cleanser is your modern oil cleanser crafted with zero compromises. Here's how it works: First, even the toughest makeup and SPF melt off with ease. Confidently use your white towels again. No makeup stains here. Second, a few splashes of water is enough with no need to tug at skin with tissue or cloths. Discover spotless skin with zero residue – no oil, waxiness, or greasiness."
    ),
    Product(
      owner_id=8, name="Power Calm Hydrating Gel Cleanser", category="Bestsellers", price=28, shortdescript="Power Calm your skin", description="The Power Calm cleanser is uniquely formulated to respect the skin's natural ecosystem while cleansing deeply and thoroughly. The result? Pure, clean skin that's hydrated and deeply calmed. We worked with our partner lab and pulled out all the stops in cosmetic wizardry to create this next-generation cleanser. Two powerful yet gentle sulfate-free cleansing agents do the heavy-lifting in drawing out impurities."
    ),
    Product(
      owner_id=8, name="Wild Dew Treatment Essence", category="Bestsellers", price=39, shortdescript="Leaves you feeling as fresh as a daisy", description="An essence may just be the missing step in your routine. Both potent and hydrating, essences not only help fight breakouts, improve skin’s radiance and impart long-lasting hydration, but they are also formulated to sink deep and fast into skin. Using next-gen technology, Peach & Lily’s nod to the Korean beauty staple includes clean, fast-acting extracts that will leave you looking and feeling fresh as a daisy."
    ),
    Product(
      owner_id=8, name="Glass Skin Refining Serum", category="Bestsellers", price=39, shortdescript="Achieve your healthiest, smoothest, clearest and most luminous skin yet", description="Glassy, smooth, luminous, translucent-looking skin is achieved when skin is well hydrated and without inflammation and free radical damage. A revolutionary cocktail of peach extract, niacinamide, East Asian mountain yam, madecassoside, peptides, and hyaluronic acid help to visibly hydrate, calm, brighten and firm skin. Crystal-clear glass skin is yours."
    ),
    Product(
      owner_id=9, name="Snail Rescue Intensive Wash-Off Mask", category="Best of Kbeauty", price=16.99, shortdescript="Targets blemishes, dark spots, pores and dullness - fast", description="Jelly isn't just for your toast. Our unique 'snail jelly' mask feels instantly refreshing and calming as it's applied onto skin. This intensive treatment clears skin and targets dark spots, blemishes, pores, and dullness. Once it's removed, all that's left is radiantly hydrated clear skin. All thanks to 95% snail mucin and cica infused with birch juice and licorice."
    ),
    Product(
      owner_id=9, name="Glass Skin Refining Serum", category="Best of Kbeauty", price=39, shortdescript="Achieve your healthiest, smoothest, clearest and most luminous skin yet", description="Glassy, smooth, luminous, translucent-looking skin is achieved when skin is well hydrated and without inflammation and free radical damage. A revolutionary cocktail of peach extract, niacinamide, East Asian mountain yam, madecassoside, peptides, and hyaluronic acid help to visibly hydrate, calm, brighten and firm skin. Crystal-clear glass skin is yours."
    ),
    Product(
      owner_id=9, name="Super Reboot Resurfacing Mask", category="Best of Kbeauty", price=42, shortdescript="Gently exfoliates, resurfaces and retexturizes skin", description="This is a pro-level wash-off mask that effectively and gently exfoliates, resurfaces and retexturizes skin. Consider this a unique deep-cleansing, purifying, and resurfacing facial where dead skin cells are unglued, impurities deep within pores are 'de-gunked' and fresh skin is revealed. If you're dealing with clogged pores, rough patches, or bumps, this mask is for you. The result? Dramatically smoother texture with drastically minimized appearance of fine lines and wrinkles. Give your skin a total reboot."
    ),
    Product(
      owner_id=9, name="Transparen-C Pro Spot Treatment", category="Best of Kbeauty", price=43, shortdescript="Stable 20% Vitamin C visibly erases dark spots - rapidly and gently", description="This powerful 20% Vitamin C spot treatment leaves dark spots, hyperpigmentation and scarring looking brighter, more even-toned and more transparent. Our professional-grade formula sinks deep into skin for dramatic, visible results. Ferulic acid and vitamin E boost brightening effects, while kojic and tranexamic acid gently renew skin for faster results. Our third party study shows visible results as early as 14 days of daily usage. "
    ),
    Product(
      owner_id=10, name="Glass Skin Water-Gel Moisturizer", category="Best of Kbeauty", price=40, shortdescript="Instantly hydrates, balances and strengthens your skin with probiotics and hyaluronic acid.", description="The perfect end to your skincare routine, our Glass Skin Water-Gel Moisturizer provides instant and long-lasting hydration for a Glass Skin glow. This breakthrough formula delivers a proprietary vegan prebiotic and probiotic complex that strengthens your skin’s unique microbiome – the environment in which your skin functions – to strengthen skin and curb breakouts. The moisturizer is also expertly blended with natural antioxidants and vitamins found in peach and kiwi extracts, combined with calming chamomile, and licorice that helps skin appear more even-toned and brighter."
    ),
    Product(
      owner_id=10, name="Lazy Day All-In-One Moisture Pads", category="Best of Kbeauty", price=39, shortdescript="Perfect for lazy – or super busy – days", description="We’ve all been there: already in bed and too tired to get up or heading straight from the gym to a night out. Because skincare doesn’t have to be all or nothing, here’s a beauty hack you can use in place of almost every step in your daily routine. Our artfully designed Lazy Day All-in-One Moisture Pads deliver the effects of a toner, essence and moisturizer in just one swipe. Packed with vitamins and antioxidants thanks to ceramides, hyaluronic acid, spinach, broccoli, carrot, pomegranate, and bamboo extracts, these hydrating pads act like a green juice for your face, imparting rich, refreshing nourishment."
    ),
    Product(
      owner_id=10, name="Lazy Day All-In-One Moisture Pads 6-ct Sample Pack", category="Best of Kbeauty", price=5, shortdescript="The perfect trial sized answer to lazy days", description="We've all been there: already in bed and too tired to get up or heading straight from the gym to a night out. Because skincare doesn't have to be all or nothing, here's a beauty hack you can use in place of almost every step in your daily routine. Our artfully designed Lazy Day All-in-One Moisture Pads deliver the effects of a toner, essence and moisturizer in just one swipe. Packed with vitamins and antioxidants thanks to ceramides, hyaluronic acid, spinach, broccoli, carrot, pomegranate, and bamboo extracts, these hydrating pads act like a green juice for your face, imparting rich, refreshing nourishment."
    ),
    Product(
      owner_id=10, name="Raw Sauce", category="Best of Kbeauty", price=43, shortdescript="Made with 79% maple tree sap", description="Raw Sauce is a gentle toner, emulsion and essence in one that intensively hydrates and nourishes the skin. What makes Raw Sauce special is that it is made with 79% maple tree sap, skin-nourishing fructan powder (eco-cert certified), and Asian herbal and fruit extracts to achieve the appearance of more hydrated and dewier skin. Perfect for all skin types."
    ),
  ]
  for product in products:
    db.session.add(product)
  db.session.commit()

def undo_products():
  db.session.execute('TRUNCATE businesses RESTART IDENTITY CASCADE;')
  db.session.commit()
